### ISSUE TITLE
[Bug] Setup via `webpack.config.js` file not working

### ISSUE THREAD

**Issue by luaz** [webpack-contrib/expose-loader#51] opened 2017-08-10 01:48 UTC
I am trying to expose jquery to be accessible via $ on external HTML/Browser Console.

The following works:
require("expose-loader?$!jquery");

This doesn't work:
```
  module: {
    rules: [
      {
        test: require.resolve('jquery'),
        // test: path.resolve(__dirname, 'src/js/jquery.js'),
        // test: "jquery",
        // test: /jquery\.js$/,
        use: [{
            loader: 'expose-loader',
            options: '$'
        }]
      }
    ],
  },
```
I was wondering did I configure it wrongly.

expose-loader: 0.7.3
webpack: 3.5.1
node: 6.11.2

**Comment by airwave-development** [comment] 2017-10-05 16:09
Same problem

**Comment by WiseBird** [comment] 2017-10-18 14:31
@luaz @airwave-development can you provide a reproduction?
I've created a [simple version](https://github.com/WiseBird/expose_loader_jquery) with the setup and it works just fine.

**Comment by WiseBird** [comment] 2017-10-18 14:41
Also this issue duplicates #20

**Comment by michael-ciniawsky** [comment] 2017-10-19 15:12
Duplicate of #20

**Closed by michael-ciniawsky** 2017-10-19 15:12 UTC
Labels: flag: Community help wanted, priority: 2 (urgent), severity: 3 (broken), type: Bug
